### Users Table
GET http://localhost:3000/users


### Registeration
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Parnika Bala",
    "email": "parnikaneeli@gmail.com",
    "password": "Parni@Teja123"
}
###
<!--{
    "name": "tejaswi ",
    "email": "tejaswiku@gmail.com",
    "password": "tejaswi@Teja123"
}-->


### Signin User
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "tejaswikurapati88@gmail.com",
    "password": "tejaswi@Teja123"
}

###

<!--{
    "email": "parnikaneeli@gmail.com",
    "password": "Parni@Teja123"
}-->
###

DELETE http://localhost:3000/users/deleteuser/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


###
GET http://localhost:3000/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA



###
GET http://localhost:3000/stocks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


###

GET http://localhost:3000/userPayment/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA

###

POST http://localhost:3000/userPayment/paymentDetails1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA
Content-Type: application/json

{
    "email": "parnikaneeli@gmail.com",
    "planId": 1,
    "billingCycle": "half year", 
    "paymentMethod": "upi",
    "upiId" : "14789526@frgr"
}
###

POST http://localhost:3000/userPayment/paymentDetails1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA
Content-Type: application/json

{
    "email": "parnikaneeli@gmail.com",
    "planId": 1,
    "billingCycle": "half year", 
    "paymentMethod": "upi",
    "cardNum" : "14789526@frgr",
    "cardExpiryDate": "2025-02-01"
}

###
POST http://localhost:3000/userPayment/paymentDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA
Content-Type: application/json

{
    "fullName" : "Tejaswi",
    "cardNumber": "12432546987521",
    "expirationDate":"2027-12-12",
    "country":"India",
    "state": "Telangana",
    "city": "Mahabubabad",
    "addressLine1": "2-2B Shivashankar cloth store",
    "addressLine2": "Bus stand road",
    "postalCode": 101505,
    "billingCycle": "Annually",
    "termsAccepted": false,
    "planId": 1
}
###

DELETE http://localhost:3000/userPayment/deleteuserpatment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### Comp stocks
GET http://localhost:3000/stocks/compstock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


###Companys_socks_list with pagination
GET http://localhost:3000/stocks/compstock/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### Nifty500
GET http://localhost:3000/stocks/nifty500/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### Nifty100 from company_stock_list
GET http://localhost:3000/stocks/nifty100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### Dummy stocks list
GET http://localhost:3000/stocks/dummycompstocks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA



### Comp stocks
GET http://localhost:3000/stocks/compstock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


###
GET http://localhost:3000/stocks/smallcap
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### mid cap company_stocks
GET http://localhost:3000/stocks/midcap
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### large cap company_stocks 
GET http://localhost:3000/stocks/largecap
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


### add userDetails in my profile
PUT http://localhost:3000/userdetails/adduser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA
Content-Type: application/json

{
    "firstName": "Parnika Bala" ,
    "lastName": "Neeli",
    "dob": "2001-12-12",
    "gender": "Female",
    "email": "parnikaneeli@gmail.com",
    "phoneNumber": "9912000000",
    "country": "India",
    "state": "Telangana",
    "city": "Mahabubabad",
    "occupation": "Full-stack Developer",
    "pincode": "506101" ,
    "industry": "finance",
    "income": "200000",
    "address": "Shiva Shankar cloth store, opposite Jio office",
    "ageGroup": "25 - 35",
    "username": "tejaswikurapati88"
}

### Update user_investment
PUT http://localhost:3000/userdetails/adduserinvestment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA
Content-Type: application/json

{
    "householdSavaings": "589641584",
    "termInsurence": "548523153",
    "healthInsurence" : "2145600",
    "currentInvestments": "6698"
}

### get user details
GET http://localhost:3000/userdetails?email=tejaswik@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA



###
GET http://localhost:3000/myportfolio/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MDEwODc2LCJleHAiOjE3MzkwMTQ0NzZ9.sEENbe-U25M8dwneynYV_pafMUVmsQE2v1gGRb-DdAA


###

POST http://localhost:3000/riskanalysis/qanda
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MTY4MjgxLCJleHAiOjE3MzkxNzE4ODF9.LgjENsQ-NqwpwOJC_XBVAi6k6Bz7cRLbzZI8Dn7i1Yg
Content-Type: application/json

{
    "age_range": "Agree",
    "income_range": "DisAgree",
    "invest_percentage_range": "11-12",
    "equity_portfolio_size": "10",
    "high_returns_high_risk_investment": "Agree",
    "major_exp_time_range": "10-11",
    "dependents": "2",
    "stress": "disagree",
    "car_insurence": "agree",
    "fear": "disagree",
    "risky_investments": "agree",
    "max_pro_loss_prepared": "frgbetwea",
    "willingToRisk_forGoodReturns": "dgrt4qe",
    "max_loss_prepared": "rgthyj6y35w",
    "uncertainty": "grhyju",
    "philosophy": "fwghjuk",
    "botheredBy_things": "fgrthyju",
    "risk_taker": "fwgthyju"
}

### get risk analysis
GET http://localhost:3000/riskanalysis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoidGVqYXN3aSBrdXJhcGF0aSIsImVtYWlsIjoidGVqYXN3aWt1cmFwYXRpODhAZ21haWwuY29tIiwiaWF0IjoxNzM5MTY5NjcxLCJleHAiOjE3MzkxNzMyNzF9.aqiGVmgrsuGmKqCL1FmT89ZWrY6sRvwQlTrKxC9TXwg

###
PUT http://localhost:3000/riskanalysis/updaterisk
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwLCJuYW1lIjoiUGFybmlrYSBCYWxhIiwiZW1haWwiOiJwYXJuaWthbmVlbGlAZ21haWwuY29tIiwiaWF0IjoxNzM5MTY4MjgxLCJleHAiOjE3MzkxNzE4ODF9.LgjENsQ-NqwpwOJC_XBVAi6k6Bz7cRLbzZI8Dn7i1Yg
Content-Type: application/json

{
    "age_range": "Agree",
    "income_range": "DisAgree",
    "invest_percentage_range": "11-12",
    "equity_portfolio_size": "10",
    "high_returns_high_risk_investment": "Agree",
    "major_exp_time_range": "10-11",
    "dependents": "2",
    "stress": "disagree",
    "car_insurence": "agree",
    "fear": "disagree",
    "risky_investments": "agree",
    "max_pro_loss_prepared": "frgbetwea",
    "willingToRisk_forGoodReturns": "dgrt4qe",
    "max_loss_prepared": "rgthyj6y35w",
    "uncertainty": "grhyju",
    "philosophy": "fwghjuk",
    "botheredBy_things": "fgrthyju",
    "risk_taker": "fwgthyju"
}
